[package]
name = "concats-registry"
publish.workspace = true
edition.workspace = true
version.workspace = true
license = "Apache-2.0"

[lib]
name = "concats_registry"
path = "src/lib.rs"

[dependencies]
concats_config = { workspace = true }
miette = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
