[package]
name = "concats-message"
publish.workspace = true
edition.workspace = true
version.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
name = "concats_message"
path = "src/lib.rs"

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
thiserror = { workspace = true }
