[package]
name = "concats-hooks"
publish.workspace = true
edition.workspace = true
version.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
name = "concats_hooks"
path = "src/lib.rs"

[dependencies]
concats_core = { workspace = true }
concats_message = { workspace = true }
dirs = { workspace = true }
git2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
