[package]
name = "concats-core"
publish.workspace = true
edition.workspace = true
version.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
name = "concats_core"
path = "src/lib.rs"

[dependencies]
concats_message = { workspace = true }
gix = { workspace = true }
ignore = { workspace = true }
imara-diff = { workspace = true }
miette = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
